"""Project Spec S0301: the Python test environment is declared and locked.

The test dependency surface lives in repository source (root ``[test]`` and
``[scientific-forecasting]`` extras plus ``api/pyproject.toml``), is compiled
by ``requirements-test.in`` and pinned exactly in
``requirements-test.lock.txt``. Static and offline: files are parsed as text
or TOML only; nothing is installed or resolved here.
"""

import re
import tomllib
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
ROOT_PYPROJECT = REPO_ROOT / "pyproject.toml"
API_PYPROJECT = REPO_ROOT / "api" / "pyproject.toml"
LOCK_INPUT = REPO_ROOT / "requirements-test.in"
LOCK = REPO_ROOT / "requirements-test.lock.txt"

DIRECT_TEST_TOOLS = {"pytest", "httpx", "pyyaml", "psycopg"}
_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")
_PIN = re.compile(r"^([a-z0-9][a-z0-9._-]*)==([A-Za-z0-9][A-Za-z0-9.+!_-]*)$")

# Values that must never appear in the dependency files.
_FORBIDDEN_CONTENT = {
    "local_absolute_path": re.compile(r"(?:^|[\s=@])(?:/home/|/Users/|/root/|/tmp/|/workspace/|[A-Za-z]:\\)"),
    "url_credentials": re.compile(r"://[^/\s:@]+(?::[^/\s@]*)?@"),
    "index_option": re.compile(r"^\s*--(?:index-url|extra-index-url|find-links|trusted-host)\b|^\s*-[if]\s", re.M),
    "editable_or_direct_reference": re.compile(r"^\s*-e\s|\s@\s|^\s*file:|git\+", re.M),
    "secret_like_assignment": re.compile(r"(?i)\b(?:token|password|secret|api[_-]?key)\s*[=:]"),
}


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _requirement_name(requirement: str) -> str:
    match = _NAME.match(requirement)
    assert match, requirement
    return _normalize(match.group(1))


def _lock_pins() -> dict[str, str]:
    pins = {}
    for line in LOCK.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = _PIN.match(stripped)
        assert match, f"not an exact third-party pin: {stripped!r}"
        pins[_normalize(match.group(1))] = match.group(2)
    return pins


def _forbidden_content(text: str) -> list[str]:
    return [name for name, pattern in _FORBIDDEN_CONTENT.items() if pattern.search(text)]


@pytest.fixture(scope="module")
def root_project() -> dict:
    return tomllib.loads(ROOT_PYPROJECT.read_text(encoding="utf-8"))["project"]


@pytest.fixture(scope="module")
def api_dependencies() -> list[str]:
    return tomllib.loads(API_PYPROJECT.read_text(encoding="utf-8"))["project"]["dependencies"]


def test_root_test_extra_declares_only_direct_test_tools(root_project, api_dependencies) -> None:
    test_extra = root_project["optional-dependencies"]["test"]
    names = {_requirement_name(requirement) for requirement in test_extra}
    assert names == DIRECT_TEST_TOOLS
    # Runtime/API dependencies keep one source of truth (api/pyproject.toml).
    assert not names & {_requirement_name(requirement) for requirement in api_dependencies}
    assert not names & {_requirement_name(r) for r in root_project["optional-dependencies"]["scientific-forecasting"]}


def test_lock_input_adds_no_requirement_and_documents_the_compile_sources() -> None:
    text = LOCK_INPUT.read_text(encoding="utf-8")
    requirement_lines = [
        line for line in text.splitlines() if line.strip() and not line.lstrip().startswith("#")
    ]
    assert requirement_lines == []
    for fragment in (
        "pip-compile --allow-unsafe --strip-extras",
        "--extra=scientific-forecasting --extra=test",
        "--output-file=requirements-test.lock.txt",
        "api/pyproject.toml pyproject.toml requirements-test.in",
        "Python 3.12",
    ):
        assert fragment in text, fragment


def test_lock_header_records_python_312_and_the_same_sources() -> None:
    header = LOCK.read_text(encoding="utf-8").split("\n\n", 1)[0]
    assert "autogenerated by pip-compile with Python 3.12" in header
    for fragment in (
        "--extra=scientific-forecasting",
        "--extra=test",
        "--output-file=requirements-test.lock.txt",
        "--strip-extras",
        "api/pyproject.toml pyproject.toml requirements-test.in",
    ):
        assert fragment in header, fragment


def test_every_locked_package_is_exactly_pinned() -> None:
    pins = _lock_pins()
    assert pins
    assert all(version for version in pins.values())


def test_lock_covers_every_declared_direct_dependency(root_project, api_dependencies) -> None:
    pins = _lock_pins()
    declared = (
        list(api_dependencies)
        + list(root_project["dependencies"])
        + list(root_project["optional-dependencies"]["scientific-forecasting"])
        + list(root_project["optional-dependencies"]["test"])
    )
    missing = sorted({_requirement_name(r) for r in declared} - set(pins))
    assert missing == []
    # PyJWT[crypto] and psycopg[binary] arrive with their extras resolved.
    for name in ("pyjwt", "cryptography", "psycopg", "psycopg-binary", "statsmodels", "pytest"):
        assert name in pins, name


def test_lock_respects_exact_api_serving_pins(api_dependencies) -> None:
    pins = _lock_pins()
    for requirement in api_dependencies:
        match = re.fullmatch(r"([A-Za-z0-9._-]+)==([^\s;]+)", requirement)
        if match:
            assert pins[_normalize(match.group(1))] == match.group(2), requirement


@pytest.mark.parametrize("path", [ROOT_PYPROJECT, LOCK_INPUT, LOCK], ids=lambda p: p.name)
def test_dependency_files_carry_no_credentials_paths_or_private_indexes(path: Path) -> None:
    assert _forbidden_content(path.read_text(encoding="utf-8")) == []


@pytest.mark.parametrize(
    "line",
    [
        "--extra-index-url https://pypi.example.invalid/simple",
        "-i https://pypi.example.invalid/simple",
        "pkg @ file:///home/operator/pkg",
        "-e /home/operator/checkout",
        "pkg==1.0 --hash=x # https://user:pass@example.invalid/",
        "token = abc",
    ],
)
def test_forbidden_content_detector_rejects_unsafe_variants(line: str) -> None:
    assert _forbidden_content(line + "\n")
